### ISSUE TITLE
Discuss implementation of various github integrations

### ISSUE THREAD

**Issue by coreydaley** [shipwright-io/community#148]
- Setup shipwright-io/.github repository:
  - [x] Yes - Completed
  - [ ] No
- Setup snyk app
  - [ ] Yes
  - [x] No - Will review at some point in future
- Setup CodeQL scanning
  - [x] Yes - Completed via https://github.com/shipwright-io/community/issues/153
  - [ ] No
- Setup regov.io app - Pending review
  - [ ] Yes
  - [ ] No
  - [x] Maybe
- Setup Codecov app - Pending review - https://github.com/shipwright-io/community/issues/162
  - [ ] Yes
  - [ ] No
  - [x] Maybe
- Setup GitHub project
  - [x] Yes - Completed
  - [ ] No
  - Setup workflow to add new issues & pull requests to project automatically
    - [x] Yes - Completed via https://github.com/shipwright-io/community/issues/150
    - [ ] No
  - Add existing issues and pull requests to project
    - [x] Yes - Created https://github.com/shipwright-io/community/issues/152
    - [ ] No
- Setup workflows/verify.yaml to run: golangci-lint, gosec, govulncheck
  - [x] Yes
  - [ ] No
- Setup workflow to apply size label to pull requests
  - [x] Yes - Completed via https://github.com/shipwright-io/community/issues/151
  - [ ] No

**Comment by qu1queee** [comment]
Some notes from the Refinement meeting today.

- To open an issue for Codecov in Shipwright/Build, in order to understand if is a good fit, based on the types of testing we have(unit/integration/e2e)
- On regov.io, @qu1queee to take a look on it(mainly to understand it)
- On CodeQL, @SaschaSchwarze0 to give it a try in Shipwright/Build.

**Comment by coreydaley** [comment]
Updates:
 - CodeQL has been enabled on all code-bearing repositories by @SaschaSchwarze0 !
 - @qu1queee Any updates on setting up Regov.io? I can give you a tour of our implementation for the gorilla organization if you would like.
 - Opened https://github.com/shipwright-io/community/issues/162 for CodeCov
