### ISSUE TITLE
[FEATURE]: SHIP-0039 Build Scheduler Options

### ISSUE THREAD

**Issue by adambkaplan** [shipwright-io/community#213]
# Feature Tracker

This is a higher level "feature tracker" for an approved enhancement proposal. Each discrete task to implement the feature should have its own child issue, linked to an appropriate Shipwright repository.

[SHIP-0039](https://github.com/shipwright-io/community/blob/main/ships/0039-build-scheduler-opts.md): Build Scheduler Options

## Child Issues

- [x] shipwright-io/build#1635
- [x] shipwright-io/build#1636
- [x] shipwright-io/build#1637
- [ ] shipwright-io/cli#260
- [ ] shipwright-io/cli#261
- [x] shipwright-io/website#117
- [x] shipwright-io/website#118
- [x] shipwright-io/website#119
- [ ] shipwright-io/website#120
- [ ] shipwright-io/website#121

**Comment by adambkaplan** [comment]
Status:

- Node selector feature https://github.com/shipwright-io/build/issues/1635 released in v0.14
- Tolerations (https://github.com/shipwright-io/build/issues/1636) and custom scheduler (https://github.com/shipwright-io/build/issues/1637 released in
