### ISSUE TITLE
CNCF Onboarding Checklist

### ISSUE THREAD

**Issue by adambkaplan** [shipwright-io/community#240]
Copied from https://github.com/cncf/sandbox/issues/131. Dropped items that CNCF staff is responsible for.

# Welcome to CNCF Project Onboarding!

This is an issue created to help onboard your project into the CNCF after the TOC has voted to accept your project into the Sandbox.
 
We would like your project to complete onboarding within one month of acceptance.

Please track your progress by using "Quote reply" to create your own copy of this checklist in an issue, so that you can update the status as you finish items.
 
## Review and understand
* [x]  The [project proposal process and requirements](https://github.com/cncf/toc/blob/main/process/README.md).
* [x]  The [services available for your project at the CNCF](https://contribute.cncf.io/resources/project-services/).
* [x]  The [CNCF IP Policy](https://github.com/cncf/foundation/blob/main/charter.md#11-ip-policy).
* [x]  The [trademark guidelines](https://www.linuxfoundation.org/legal/trademark-usage).
* [x]  The [license allowlist](https://github.com/cncf/foundation/blob/main/allowed-third-party-license-policy.md#approved-licenses-for-allowlist).
* [x]  The [online program guidelines](https://github.com/cncf/foundation/blob/main/online-programs-guidelines.md).
* [x]  Optional: [Book time with CNCF staff](http://project-meetings.cncf.io) for any onboarding questions.
 
## Contribute and transfer
* [x]  Move your project to its own separate neutral GitHub organization. This will make it transferable to the CNCF's GitHub Enterprise account. If it's already in a GHE account, you will need to remove it from that first.
* [x]  Accept the invite to join the CNCF GitHub Enterprise account. We'll then add `thelinuxfoundation` as an organization owner to ensure neutral hosting of your project.
* [x]  Migrate your Slack channels (if any) to the [Kubernetes or CNCF Slack workspace](https://slack.com/help/articles/217872578-Import-data-from-one-Slack-workspace-to-another). CNCF staff can help.
* [x]  Submit a [pull request](https://github.com/cncf/landscape/pulls) to add your project as a Sandbox project to the [Cloud Native Landscape](https://landscape.cncf.io) by updating [landscape.yml](https://github.com/cncf/landscape/blob/master/landscape.yml) following these [instructions](https://github.com/cncf/landscape2/blob/main/docs/config/data.yml). https://github.com/cncf/landscape/pull/4035
* [x]  Transfer [your domain to the CNCF](https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63). The "LF Stakeholder email" is [projects@cncf.io](mailto:projects@cncf.io).
* [x]  Transfer any [trademark and logo assets to the Linux Foundation](https://github.com/cncf/foundation/tree/main/agreements).
* [x] Submit a [pull request](https://github.com/cncf/artwork) with your artwork. https://github.com/cncf/artwork/pull/507
* [ ]  Transfer website analytics to [projects@cncf.io](mailto:projects@cncf.io). CNCF staff can help.
 
## Update and document
* [x]  Ensure that [DCO](https://github.com/apps/dco) (preferred) or [CLA](https://github.com/cncf/cla) are enabled for all GitHub repositories of the project.
* [x]  Ensure that that the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md) (or your adopted version of it) are explicitly referenced at the project's `README` on GitHub. https://github.com/shipwright-io/.github/pull/5
* [x]  Ensure LF footer is on your website and [guidelines](https://github.com/cncf/foundation/blob/main/website-guidelines.md) are followed (if your project doesn't have a dedicated website, please adopt those guidelines for the `README` file). https://github.com/shipwright-io/website/pull/131
* [x]  Create a maintainer list and add it to the [aggregated CNCF maintainer list](https://maintainers.cncf.io) via pull request. https://github.com/shipwright-io/community/pull/242 and https://github.com/cncf/foundation/pull/860
* [x]  Provide emails for the maintainers to get access to the maintainers mailing list and Service Desk. Email them to [project-onboarding@cncf.io](mailto:project-onboarding@cncf.io). Email sent.
* [x]  Start working on [written, open governance](https://contribute.cncf.io/maintainers/governance/). https://github.com/shipwright-io/community/issues/243
* [x]  Start on an [OpenSSF Best Practices Badge](https://www.bestpractices.dev/en).

**Comment by qu1queee** [comment]
Some updates:

- Website PR for including CNCF trademark,etc https://github.com/shipwright-io/website/pull/130
- PR for updating our entry in the CNCF landscape https://github.com/cncf/landscape/pull/4035
- DOC is enabled now in all repositories of the Shipwright github org
- Meeting with CNCF staff is already scheduled

**Comment by adambkaplan** [comment]
> [ ] Transfer any [trademark and logo assets to the Linux Foundation](https://github.com/cncf/foundation/tree/main/agreements).

We should check with Michelle Martineau or Todd Moore - I _think _ this already "done" no actual paperwork needs to be filled out.

**Comment by adambkaplan** [comment]
Per Red Hat OSPO - the shipwright.io domain registration was already transferred to the Linux Foundation when the project was donated to the CDF. Domain transfer to the CNCF will either be a no-op or a matter of updating records on the LF side of things.

**Comment by adambkaplan** [comment]
@qu1queee I think we can call this "Done" - we do have follow ups for the following:

- Governance #243 
- CNCF access to our Netlify account (we should probably create a community issue for this, assigned to me)
- Bake off of Snyk vs. FOSSA for licence compliance checks - do we have an issue here?

Any other follow ups I'm missing?

**Comment by adambkaplan** [comment]
Declaring this "Done" - the only remaining item was the website analytics, which we in fact didn't have in the CD Foundation. We now have Google Analytics through the CNCF.
